-- =====================================================
-- ESRS S3 (Ovplyvnené komunity) - Slovak Translations
-- =====================================================

-- S3.SBM-3: Strategy and Business Model
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Všetky ovplyvnené komunity, ktoré môžu byť významne ovplyvnené podnikom, sú zahrnuté v rozsahu zverejnenia podľa ESRS 2') WHERE code = 'S3.SBM-3_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis typov ovplyvnených komunít podliehajúcich významným dopadom') WHERE code = 'S3.SBM-3_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Typ komunít podliehajúcich významným dopadom vlastnými činnosťami alebo prostredníctvom hodnotového reťazca') WHERE code = 'S3.SBM-3_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Výskyt významných negatívnych dopadov (ovplyvnené komunity)') WHERE code = 'S3.SBM-3_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis činností, ktoré majú pozitívne dopady, a typy ovplyvnených komunít, ktoré sú alebo môžu byť pozitívne ovplyvnené') WHERE code = 'S3.SBM-3_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis významných rizík a príležitostí vyplývajúcich z dopadov a závislostí na ovplyvnených komunitách') WHERE code = 'S3.SBM-3_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako podnik rozvinul pochopenie toho, ako môžu byť ovplyvnené komunity s osobitnými charakteristikami alebo žijúce v osobitných podmienkach vystavené vyššiemu riziku poškodenia') WHERE code = 'S3.SBM-3_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ktoré zo významných rizík a príležitostí vyplývajúcich z dopadov a závislostí na ovplyvnených komunitách sú dopadmi na konkrétne skupiny') WHERE code = 'S3.SBM-3_08';

-- S3-1: Policies
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Politiky na riadenie významných dopadov, rizík a príležitostí týkajúcich sa ovplyvnených komunít [pozri ESRS 2 MDR-P]') WHERE code = 'S3.MDR-P_01-06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie akýchkoľvek osobitných politických ustanovení na predchádzanie a riešenie dopadov na pôvodné obyvateľstvo') WHERE code = 'S3-1_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis relevantných záväzkov v oblasti politiky ľudských práv týkajúcich sa ovplyvnených komunít') WHERE code = 'S3-1_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu vo vzťahu k rešpektovaniu ľudských práv komunít a konkrétne pôvodného obyvateľstva') WHERE code = 'S3-1_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu vo vzťahu k zapojeniu ovplyvnených komunít') WHERE code = 'S3-1_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu vo vzťahu k opatreniam na zabezpečenie a (alebo) umožnenie nápravy dopadov na ľudské práva') WHERE code = 'S3-1_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako sú politiky zosúladené s príslušnými medzinárodne uznávanými nástrojmi') WHERE code = 'S3-1_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie rozsahu a uvedenie povahy prípadov nedodržania Usmernení OSN pre podnikanie a ľudské práva, Deklarácie MOP o základných princípoch a právach pri práci alebo Usmernení OECD pre nadnárodné podniky, ktoré zahŕňajú ovplyvnené komunity') WHERE code = 'S3-1_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie vysvetlenia významných zmien prijatých politík počas vykazovacieho roka') WHERE code = 'S3-1_08';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie o ilustrácii typov komunikácie svojich politík jednotlivcom, skupine jednotlivcov alebo subjektom, pre ktoré sú relevantné') WHERE code = 'S3-1_09';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenia, ktoré sa majú vykazovať v prípade, že podnik neprijal politiky') WHERE code = 'S3.MDR-P_07-08';

-- S3-2: Engagement with affected communities
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako perspektívy ovplyvnených komunít ovplyvňujú rozhodnutia alebo činnosti zamerané na riadenie skutočných a potenciálnych dopadov') WHERE code = 'S3-2_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zapojenie sa uskutočňuje s ovplyvnenými komunitami alebo ich legitímnymi zástupcami priamo alebo s dôveryhodnými zástupcami') WHERE code = 'S3-2_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie štádia, v ktorom dochádza k zapojeniu, typu zapojenia a frekvencie zapojenia') WHERE code = 'S3-2_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie funkcie a najvyššej pozície v rámci podniku, ktorá má operatívnu zodpovednosť za zabezpečenie zapojenia a za to, že výsledky informujú o prístupe podniku') WHERE code = 'S3-2_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ako podnik hodnotí účinnosť svojho zapojenia ovplyvnených komunít') WHERE code = 'S3-2_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie krokov prijatých na získanie prehľadu o perspektívach ovplyvnených komunít, ktoré môžu byť obzvlášť zraniteľné voči dopadom a (alebo) marginalizované') WHERE code = 'S3-2_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako podnik zohľadňuje a zabezpečuje rešpektovanie osobitných práv pôvodného obyvateľstva vo svojom prístupe k zapojeniu zainteresovaných strán') WHERE code = 'S3-2_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Vyhlásenie v prípade, že podnik neprijal všeobecný proces na zapojenie ovplyvnených komunít') WHERE code = 'S3-2_08';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie časového harmonogramu prijatia všeobecného procesu na zapojenie ovplyvnených komunít v prípade, že podnik neprijal všeobecný proces zapojenia') WHERE code = 'S3-2_09';

-- S3-3: Processes to remediate negative impacts and channels for affected communities to raise concerns
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu a procesov na poskytovanie alebo prispievanie k náprave, keď podnik identifikoval, že je spojený so významným negatívnym dopadom na ovplyvnené komunity') WHERE code = 'S3-3_10';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie konkrétnych kanálov, ktoré majú ovplyvnené komunity k dispozícii na priame vznesenie obav alebo potrieb s podnikom a ich riešenie') WHERE code = 'S3-3_11';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie procesov, prostredníctvom ktorých podnik podporuje alebo vyžaduje dostupnosť kanálov') WHERE code = 'S3-3_12';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ako sú vznesené a riešené otázky sledované a monitorované a ako je zabezpečená účinnosť kanálov') WHERE code = 'S3-3_13';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako sa hodnotí, že ovplyvnené komunity si sú vedomé štruktúr alebo procesov a dôverujú im ako spôsobu, ako vyjadriť svoje obavy alebo potreby a nechať ich riešiť') WHERE code = 'S3-3_14';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Politiky týkajúce sa ochrany pred odvetou pre jednotlivcov, ktorí používajú kanály na vznesenie obav alebo potrieb, sú zavedené') WHERE code = 'S3-3_15';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Vyhlásenie v prípade, že podnik neprijal všeobecný proces na zapojenie ovplyvnených komunít') WHERE code = 'S3-3_16';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie časového harmonogramu zavedenia kanálov alebo procesov na vznesenie obav') WHERE code = 'S3-3_17';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako majú ovplyvnené komunity prístup ku kanálom na úrovni podniku, ktorým sú ovplyvnené') WHERE code = 'S3-3_18';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Mechanizmy tretích strán sú prístupné všetkým ovplyvneným komunitám') WHERE code = 'S3-3_19';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Sťažnosti sa riešia dôverne a s rešpektovaním práva na súkromie a ochranu údajov') WHERE code = 'S3-3_20';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Ovplyvnené komunity majú možnosť používať kanály na vznesenie obáv alebo potrieb anonymne') WHERE code = 'S3-3_21';

-- S3-4: Actions
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Akčné plány a zdroje na riadenie významných dopadov, rizík a príležitostí týkajúcich sa ovplyvnených komunít [pozri ESRS 2 - MDR-A]') WHERE code = 'S3.MDR-A_01-12';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis prijatých, plánovaných alebo prebiehajúcich opatrení na predchádzanie, zmiernenie alebo nápravu významných negatívnych dopadov na ovplyvnené komunity') WHERE code = 'S3-4_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis, či a ako podnik prijal opatrenia na poskytnutie alebo umožnenie nápravy vo vzťahu k skutočnému významnému dopadu') WHERE code = 'S3-4_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis dodatočných iniciatív alebo procesov, ktorých primárnym účelom je poskytovanie pozitívnych dopadov pre ovplyvnené komunity') WHERE code = 'S3-4_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis toho, ako sa sleduje a hodnotí účinnosť opatrení alebo iniciatív pri dosahovaní výsledkov pre ovplyvnené komunity') WHERE code = 'S3-4_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis procesov identifikácie toho, aké opatrenie je potrebné a vhodné v reakcii na konkrétny skutočný alebo potenciálny významný negatívny dopad na ovplyvnené komunity') WHERE code = 'S3-4_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis prístupu k prijímaniu opatrení vo vzťahu ku konkrétnym významným negatívnym dopadom na ovplyvnené komunity') WHERE code = 'S3-4_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis prístupu k zabezpečeniu, že procesy na poskytovanie alebo umožnenie nápravy v prípade významných negatívnych dopadov na ovplyvnené komunity sú dostupné a účinné v ich implementácii a výsledkoch') WHERE code = 'S3-4_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis toho, aké opatrenie je plánované alebo prebieha na zmiernenie významných rizík vyplývajúcich z dopadov a závislostí na ovplyvnených komunitách a ako sa sleduje účinnosť') WHERE code = 'S3-4_08';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis toho, aké opatrenie je plánované alebo prebieha na využitie významných príležitostí vo vzťahu k ovplyvneným komunitám') WHERE code = 'S3-4_09';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako sa zabezpečuje, že vlastné postupy nespôsobujú ani neprispievajú k významným negatívnym dopadom na ovplyvnené komunity') WHERE code = 'S3-4_10';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie závažných otázok a incidentov v oblasti ľudských práv spojených s ovplyvnenými komunitami') WHERE code = 'S3-4_11';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie zdrojov pridelených na riadenie významných dopadov') WHERE code = 'S3-4_12';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako sa podnik snaží využiť vplyv s relevantnými obchodnými vzťahmi na riadenie významných negatívnych dopadov ovplyvňujúcich ovplyvnené komunity') WHERE code = 'S3-4_13';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ako je účasť v priemyselnej alebo viacstrannej iniciatíve a vlastné zapojenie podniku zamerané na riešenie významných dopadov') WHERE code = 'S3-4_14';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako ovplyvnené komunity zohrávajú úlohu v rozhodnutiach týkajúcich sa návrhu a implementácie programov alebo investícií') WHERE code = 'S3-4_15';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Informácie o zamýšľaných alebo dosiahnutých pozitívnych výsledkoch programov alebo investícií pre ovplyvnené komunity') WHERE code = 'S3-4_16';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Vysvetlenie približného rozsahu ovplyvnených komunít pokrytých opisovanými programami sociálnych investícií alebo rozvoja a, kde je to možné, odôvodnenie, prečo boli vybrané konkrétne komunity') WHERE code = 'S3-4_17';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Iniciatívy alebo procesy, ktorých primárnym cieľom je poskytovanie pozitívnych dopadov pre ovplyvnené komunity, jsou navrhnuté aj na podporu dosiahnutia jedného alebo viacerých Cieľov udržateľného rozvoja') WHERE code = 'S3-4_18';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis interných funkcií, ktoré sa podieľajú na riadení dopadov a typy opatrení prijatých internými funkciami na riešenie negatívnych a podporu pozitívnych dopadov') WHERE code = 'S3-4_19';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenia, ktoré sa majú vykazovať, ak podnik neprijal opatrenia') WHERE code = 'S3.MDR-A_13-14';

-- S3-5: Targets
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Ciele stanovené na riadenie významných dopadov, rizík a príležitostí týkajúcich sa ovplyvnených komunít [pozri ESRS 2 - MDR-T]') WHERE code = 'S3.MDR-T_01-13';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako boli ovplyvnené komunity priamo zapojené do stanovovania cieľov') WHERE code = 'S3-5_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako boli ovplyvnené komunity priamo zapojené do sledovania výkonnosti voči cieľom') WHERE code = 'S3-5_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako boli ovplyvnené komunity priamo zapojené do identifikácie poučení alebo zlepšení ako výsledku výkonnosti podniku') WHERE code = 'S3-5_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie zamýšľaných výsledkov, ktoré sa majú dosiahnuť v životoch ovplyvnených komunít') WHERE code = 'S3-5_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Informácie o stabilite cieľa v priebehu času z hľadiska definícií a metodík na umožnenie porovnateľnosti') WHERE code = 'S3-5_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie odkazov na štandardy alebo záväzky, na ktorých je cieľ založený') WHERE code = 'S3-5_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenia, ktoré sa majú vykazovať, ak podnik neprijal ciele') WHERE code = 'S3.MDR-T_14-19';

-- =====================================================
-- ESRS S4 (Spotrebitelia a koncoví používatelia) - Slovak Translations
-- =====================================================

-- S4.SBM-3: Strategy and Business Model
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Všetci spotrebitelia a koncoví používatelia, ktorí môžu byť významne ovplyvnení podnikom, sú zahrnutí v rozsahu zverejnenia podľa ESRS 2') WHERE code = 'S4.SBM-3_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis typov spotrebiteľov a koncových používateľov podliehajúcich významným dopadom') WHERE code = 'S4.SBM-3_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Typ spotrebiteľov a koncových používateľov podliehajúcich významným dopadom vlastnými činnosťami alebo prostredníctvom hodnotového reťazca') WHERE code = 'S4.SBM-3_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Výskyt významných negatívnych dopadov (spotrebitelia a koncoví používatelia)') WHERE code = 'S4.SBM-3_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis činností, ktoré majú pozitívne dopady, a typy spotrebiteľov a koncových používateľov, ktorí sú alebo môžu byť pozitívne ovplyvnení') WHERE code = 'S4.SBM-3_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis významných rizík a príležitostí vyplývajúcich z dopadov a závislostí na spotrebiteľoch a koncových používateľoch') WHERE code = 'S4.SBM-3_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako bolo rozvinuté pochopenie toho, ako môžu byť spotrebitelia a koncoví používatelia s osobitnými charakteristikami, pracujúci v osobitných podmienkach alebo vykonávajúci osobitné činnosti vystavení vyššiemu riziku poškodenia') WHERE code = 'S4.SBM-3_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ktoré zo významných rizík a príležitostí vyplývajúcich z dopadov a závislostí na spotrebiteľoch a koncových používateľoch sú dopadmi na konkrétne skupiny') WHERE code = 'S4.SBM-3_08';

-- S4-1: Policies
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Politiky na riadenie významných dopadov, rizík a príležitostí týkajúcich sa spotrebiteľov a koncových používateľov [pozri ESRS 2 MDR-P]') WHERE code = 'S4.MDR-P_01-06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Politiky na riadenie významných dopadov, rizík a príležitostí týkajúcich sa ovplyvnených spotrebiteľov a koncových používateľov, vrátane špecifických skupín alebo všetkých spotrebiteľov / koncových používateľov') WHERE code = 'S4-1_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis relevantných záväzkov v oblasti politiky ľudských práv týkajúcich sa spotrebiteľov a (alebo) koncových používateľov') WHERE code = 'S4-1_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu vo vzťahu k rešpektovaniu ľudských práv spotrebiteľov a koncových používateľov') WHERE code = 'S4-1_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu vo vzťahu k zapojeniu spotrebiteľov a (alebo) koncových používateľov') WHERE code = 'S4-1_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu vo vzťahu k opatreniam na zabezpečenie a (alebo) umožnenie nápravy dopadov na ľudské práva') WHERE code = 'S4-1_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis, či a ako sú politiky zosúladené s príslušnými medzinárodne uznávanými nástrojmi') WHERE code = 'S4-1_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie rozsahu a uvedenie povahy prípadov nedodržania Usmernení OSN pre podnikanie a ľudské práva, Deklarácie MOP o základných princípoch a právach pri práci alebo Usmernení OECD pre nadnárodné podniky, ktoré zahŕňajú spotrebiteľov a (alebo) koncových používateľov') WHERE code = 'S4-1_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie vysvetlenia významných zmien prijatých politík počas vykazovacieho roka') WHERE code = 'S4-1_08';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie o ilustrácii typov komunikácie svojich politík jednotlivcom, skupine jednotlivcov alebo subjektom, pre ktoré sú relevantné') WHERE code = 'S4-1_09';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenia, ktoré sa majú vykazovať v prípade, že podnik neprijal politiky') WHERE code = 'S4.MDR-P_07-08';

-- S4-2: Engagement with consumers and end-users
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako perspektívy spotrebiteľov a koncových používateľov ovplyvňujú rozhodnutia alebo činnosti zamerané na riadenie skutočných a potenciálnych dopadov') WHERE code = 'S4-2_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zapojenie sa uskutočňuje so spotrebiteľmi a koncovými používateľmi alebo ich legitímnymi zástupcami priamo alebo s dôveryhodnými zástupcami') WHERE code = 'S4-2_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie štádia, v ktorom dochádza k zapojeniu, typu zapojenia a frekvencie zapojenia') WHERE code = 'S4-2_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie funkcie a najvyššej pozície v rámci podniku, ktorá má operatívnu zodpovednosť za zabezpečenie zapojenia a za to, že výsledky informujú o prístupe podniku') WHERE code = 'S4-2_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ako sa hodnotí účinnosť zapojenia so spotrebiteľmi a koncovými používateľmi') WHERE code = 'S4-2_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie krokov prijatých na získanie prehľadu o perspektívach spotrebiteľov a koncových používateľov / spotrebiteľov a koncových používateľov, ktorí môžu byť obzvlášť zraniteľní voči dopadom a (alebo) marginalizovaní') WHERE code = 'S4-2_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Vyhlásenie v prípade, že podnik neprijal všeobecný proces na zapojenie spotrebiteľov a (alebo) koncových používateľov') WHERE code = 'S4-2_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie časového harmonogramu prijatia všeobecného procesu na zapojenie spotrebiteľov a koncových používateľov v prípade, že podnik neprijal všeobecný proces zapojenia') WHERE code = 'S4-2_08';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Typ úlohy alebo funkcie, ktorá sa zaoberá zapojením') WHERE code = 'S4-2_09';

-- S4-3: Processes to remediate negative impacts and channels for consumers and end-users to raise concerns
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie všeobecného prístupu a procesov na poskytovanie alebo prispievanie k náprave, keď podnik identifikoval, že je spojený so významným negatívnym dopadom na spotrebiteľov a koncových používateľov') WHERE code = 'S4-3_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie konkrétnych kanálov, ktoré majú spotrebitelia a koncoví používatelia k dispozícii na priame vznesenie obáv alebo potrieb s podnikom a ich riešenie') WHERE code = 'S4-3_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie procesov, prostredníctvom ktorých podnik podporuje alebo vyžaduje dostupnosť kanálov') WHERE code = 'S4-3_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ako sú vznesené a riešené otázky sledované a monitorované a ako je zabezpečená účinnosť kanálov') WHERE code = 'S4-3_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako sa hodnotí, že spotrebitelia a koncoví používatelia si sú vedomí štruktúr alebo procesov a dôverujú im ako spôsobu, ako vyjadriť svoje obavy alebo potreby a nechať ich riešiť') WHERE code = 'S4-3_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Politiky týkajúce sa ochrany pred odvetou pre jednotlivcov, ktorí používajú kanály na vznesenie obáv alebo potrieb, sú zavedené') WHERE code = 'S4-3_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Vyhlásenie v prípade, že podnik neprijal všeobecný proces na zapojenie spotrebiteľov a (alebo) koncových používateľov') WHERE code = 'S4-3_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie časového harmonogramu zavedenia kanálov alebo procesov na vznesenie obáv') WHERE code = 'S4-3_08';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako majú spotrebitelia a (alebo) koncoví používatelia prístup ku kanálom na úrovni podniku, ktorým sú ovplyvnení') WHERE code = 'S4-3_09';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Mechanizmy tretích strán sú prístupné všetkým spotrebiteľom a (alebo) koncovým používateľom') WHERE code = 'S4-3_10';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Sťažnosti sa riešia dôverne a s rešpektovaním práva na súkromie a ochranu údajov') WHERE code = 'S4-3_11';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Spotrebitelia a koncoví používatelia majú možnosť používať kanály na vznesenie obáv alebo potrieb anonymne') WHERE code = 'S4-3_12';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Počet sťažností prijatých od spotrebiteľov a (alebo) koncových používateľov počas vykazovacieho obdobia') WHERE code = 'S4-3_13';

-- S4-4: Actions
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Akčné plány a zdroje na riadenie významných dopadov, rizík a príležitostí týkajúcich sa spotrebiteľov a koncových používateľov [pozri ESRS 2 - MDR-A]') WHERE code = 'S4.MDR-A_01-12';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis plánovaných alebo prebiehajúcich opatrení na predchádzanie, zmiernenie alebo nápravu významných negatívnych dopadov na spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis, či a ako boli prijaté opatrenia na poskytnutie alebo umožnenie nápravy vo vzťahu k skutočnému významnému dopadu') WHERE code = 'S4-4_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis dodatočných iniciatív alebo procesov, ktorých primárnym účelom je poskytovanie pozitívnych dopadov pre spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis toho, ako sa sleduje a hodnotí účinnosť opatrení alebo iniciatív pri dosahovaní výsledkov pre spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis prístupu k identifikácii toho, aké opatrenie je potrebné a vhodné v reakcii na konkrétny skutočný alebo potenciálny významný negatívny dopad na spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis prístupu k prijímaniu opatrení vo vzťahu ku konkrétnym významným dopadom na spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis prístupu k zabezpečeniu, že procesy na poskytovanie alebo umožnenie nápravy v prípade významných negatívnych dopadov na spotrebiteľov a koncových používateľov sú dostupné a účinné v ich implementácii a výsledkoch') WHERE code = 'S4-4_07';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis toho, aké opatrenie je plánované alebo prebieha na zmiernenie významných rizík vyplývajúcich z dopadov a závislostí na spotrebiteľoch a koncových používateľoch a ako sa sleduje účinnosť') WHERE code = 'S4-4_08';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis toho, aké opatrenie je plánované alebo prebieha na využitie významných príležitostí vo vzťahu k spotrebiteľom a koncovým používateľom') WHERE code = 'S4-4_09';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako sa zabezpečuje, že vlastné postupy nespôsobujú ani neprispievajú k významným negatívnym dopadom na spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_10';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie závažných otázok a incidentov v oblasti ľudských práv spojených so spotrebiteľmi a (alebo) koncovými používateľmi') WHERE code = 'S4-4_11';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie zdrojov pridelených na riadenie významných dopadov') WHERE code = 'S4-4_12';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako sa podnik snaží využiť vplyv s relevantnými obchodnými vzťahmi na riadenie významných negatívnych dopadov ovplyvňujúcich spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_13';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ako je účasť v priemyselnej alebo viacstrannej iniciatíve a vlastné zapojenie podniku zamerané na riešenie významných dopadov') WHERE code = 'S4-4_14';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, ako spotrebitelia a koncoví používatelia zohrávajú úlohu v rozhodnutiach týkajúcich sa návrhu a implementácie programov alebo procesov') WHERE code = 'S4-4_15';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Informácie o zamýšľaných alebo dosiahnutých pozitívnych výsledkoch programov alebo procesov pre spotrebiteľov a koncových používateľov') WHERE code = 'S4-4_16';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Iniciatívy alebo procesy, ktorých primárnym cieľom je poskytovanie pozitívnych dopadov pre spotrebiteľov a (alebo) koncových používateľov, sú navrhnuté aj na podporu dosiahnutia jedného alebo viacerých Cieľov udržateľného rozvoja') WHERE code = 'S4-4_17';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Opis interných funkcií, ktoré sa podieľajú na riadení dopadov a typy opatrení prijatých internými funkciami na riešenie negatívnych a podporu pozitívnych dopadov') WHERE code = 'S4-4_18';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenia, ktoré sa majú vykazovať, ak podnik neprijal opatrenia') WHERE code = 'S4.MDR-A_13-14';

-- S4-5: Targets
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Ciele stanovené na riadenie významných dopadov, rizík a príležitostí týkajúcich sa spotrebiteľov a koncových používateľov [pozri ESRS 2 - MDR-T]') WHERE code = 'S4.MDR-T_01-13';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako boli spotrebitelia a koncoví používatelia priamo zapojení do stanovovania cieľov') WHERE code = 'S4-5_01';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako boli spotrebitelia a koncoví používatelia priamo zapojení do sledovania výkonnosti voči cieľom') WHERE code = 'S4-5_02';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie, či a ako boli spotrebitelia a koncoví používatelia priamo zapojení do identifikácie poučení alebo zlepšení ako výsledku výkonnosti podniku') WHERE code = 'S4-5_03';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie zamýšľaných výsledkov, ktoré sa majú dosiahnuť v životoch spotrebiteľov a koncových používateľov') WHERE code = 'S4-5_04';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Informácie o stabilite cieľa v priebehu času z hľadiska definícií a metodík na umožnenie porovnateľnosti') WHERE code = 'S4-5_05';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenie odkazov na štandardy alebo záväzky, na ktorých je cieľ založený') WHERE code = 'S4-5_06';
UPDATE disclosure_question SET translations = translations || jsonb_build_object('sk', 'Zverejnenia, ktoré sa majú vykazovať, ak podnik neprijal ciele') WHERE code = 'S4.MDR-T_14-19';
