INSERT INTO vsme_datapoint(id, module, level, label_en, value_type, unit) VALUES
('AddressOfSite', 'B1', 'core', 'Address', 'string', NULL),
('AmountOfEmissionToAir', 'B4', 'core', 'Emission to air', 'number', NULL),
('AmountOfEmissionToSoil', 'B4', 'core', 'Emission to soil', 'number', NULL),
('AmountOfEmissionToWater', 'B4', 'core', 'Emission to water', 'number', NULL),
('AmountOfWaterWithdrawnAtSitesLocatedInAreasOfHighWaterStress', 'B6', 'core', 'Amount of water withdrawn at sites located in areas of high water-stress (cubic meters m)', 'number', NULL),
('AreaOfSiteInBiodiversitySensitiveArea', 'B5', 'core', 'Area (hectares or m based on the selection above)', 'number', NULL),
('Assets', 'B1', 'core', 'Size of balance sheet (total assets) in', 'number', NULL),
('AverageNumberOfAnnualTrainingHoursPerFemaleEmployee', 'B10', 'core', 'Female', 'number', NULL),
('AverageNumberOfAnnualTrainingHoursPerMaleEmployee', 'B10', 'core', 'Male', 'number', NULL),
('AverageNumberOfAnnualTrainingHoursPerNonReportedGenderEmployee', 'B10', 'core', 'Not reported', 'number', NULL),
('AverageNumberOfAnnualTrainingHoursPerOtherGenderEmployee', 'B10', 'core', 'Other', 'number', NULL),
('BasisForPreparation', 'B1', 'core', 'Basis for preparation (Basic Module Only or Basic & Comprehensive Module)', 'enum', NULL),
('BasisForReporting', 'B1', 'core', 'Basis for reporting (consolidated or individual basis)', 'enum', NULL),
('CityOfSite', 'B1', 'core', 'City', 'string', NULL),
('CountryOfPrimaryOperationsAndLocationOfSignificantAssets', 'B1', 'core', 'Country of primary operations and location of significant asset(s)', 'string', NULL),
('CountryOfSite', 'B1', 'core', 'Country', 'enum', NULL),
('DescriptionOfActionsTakeToAddressTheConfirmedIncidents', 'C7', 'comprehensive', 'Description of actions taken to address the confirmed incidents', 'string', NULL),
('DescriptionOfATargetRelatedToAPolicy', 'C2', 'comprehensive', 'Description of target related to a policy', 'string', NULL),
('DescriptionOfATransitionPlanForClimateChangeMitigationIncludingAnExplanationOfHowItIsContributingToReduceGhgEmissions', 'C3', 'comprehensive', 'Description of a transition plan for climate change mitigation including an explanation of how it is contributing to reduce GHG emissions May (optional)', 'string', NULL),
('DescriptionOfClimateRelatedHazardsAndClimateRelatedTransitionEvents', 'C4', 'comprehensive', 'Description of climate-related hazards and climate-related transition events', 'string', NULL),
('DescriptionOfHowCircularEconomyPrinciplesAreApplied', 'B7', 'core', 'Description of how it applies these principles', 'string', NULL),
('DescriptionOfKeyElementsOfStrategyThatRelatesToOrAffectsSustainabilityIssues', 'C1', 'comprehensive', 'Description of those key elements in the strategy that relate or affect sustainability issues', 'string', NULL),
('DescriptionOfLimitsToTheDistributionOfProfitsConnectedToTheMutualisticNatureOrToTheNatureOfTheActivitiesConsistingInServicesOfGeneralEconomicInterestSGEI', 'B2', 'core', 'Any limits to the distribution of profits connected to the mutualistic nature or to the nature of the activities consisting in services of general economic interest (SGEI)', 'string', NULL),
('DescriptionOfMainBusinessRelationships', 'C1', 'comprehensive', 'Description of main business relationships (such as key suppliers, customers, distribution channels)', 'string', NULL),
('DescriptionOfPracticesPoliciesAndOrFutureInitiatives', 'C2', 'comprehensive', 'Description of a practice policy and or future initiative towards a more sustainable future (In case the practice  policy  future initiative covers suppliers or clients the undertaking shall mention it)', 'string', NULL),
('DescriptionOfSignificantGroupsOfProductsAndOrServicesOffered', 'C1', 'comprehensive', 'Description of significant groups of products and or services offered', 'string', NULL),
('DescriptionOfSignificantMarketsTheUndertakingOperatesIn', 'C1', 'comprehensive', 'Description of significant market(s) the undertaking operates in (e.g. B2B, wholesale, retail, countries)', 'string', NULL),
('DescriptionOfSustainabilityRelatedCertificationsOrLabels', 'B1', 'core', 'Description of sustainability-related certification(s) or label(s) including where relevant the issuers of the certification or label date and rating score', 'string', NULL),
('DescriptionOfTheEffectiveParticipationOfWorkersUsersOrOtherInterestedPartiesOrCommunitiesInGovernance', 'B2', 'core', 'Effective participation of workers users or other interested parties or communities in governance', 'string', NULL),
('DisclosureOfAnyOtherEnvironmentalAndOrEntitySpecificEnvironmentalDisclosures', 'C4', 'comprehensive', 'Disclosure of any other environmental and or entity specific environmental disclosures from to [May (optional)]', 'string', NULL),
('DisclosureOfAnyOtherGeneralAndOrEntitySpecificInformation', 'C1', 'comprehensive', 'Disclosure of any other general and or entity specific information on the reporting period from to [May (optional)]', 'string', NULL),
('DisclosureOfAnyOtherGovernanceAndOrEntitySpecificGovernanceDisclosures', 'C9', 'comprehensive', 'Disclosure of any other governance and or entity specific governance disclosures from to [May (optional)]', 'string', NULL),
('DisclosureOfAnyOtherSocialAndOrEntitySpecificSocialDisclosures', 'C7', 'comprehensive', 'Disclosure of any other social and or entity specific social disclosures from to [May (optional)]', 'string', NULL),
('DisclosureOfHowItHasAssessedTheExposureAndSensitivityOfItsAssetsActivitiesAndValueChainToTheseHazardsAndTransitionEvents', 'C4', 'comprehensive', 'Disclosure of how it has assessed the exposure and sensitivity of its assets activities and value chain to these hazards and transition events', 'string', NULL),
('DisclosureOfListOfMainActionsTheEntitySeeksInOrderToAchieveItsTargets', 'C3', 'comprehensive', 'C3 - Disclosure of list of main actions the entity seeks in order to achieve its targets from to [If applicable]', 'string', NULL),
('DisclosureOfWhetherItHasUndertakenClimateChangeAdaptationActionsForAnyClimateRelatedHazardsAndTransitionEvents', 'C4', 'comprehensive', 'Disclosure of whether it has undertaken climate change adaptation actions for any climate-related hazards and transition events', 'enum', NULL),
('EmployeeCountingMethodology', 'B1', 'core', 'Employee counting methodology (At the end of reporting period or as an average during the reporting period)', 'enum', NULL),
('EmployeesReceivePayEqualOrAboveMinimumWageDeterminedByNationalLawOrCollectiveAgreement', 'B10', 'core', 'Employees receive pay that is equal or above applicable minimum wage determined directly by the national minimum wage law or through a collective bargaining agreement', 'enum', NULL),
('FinancialInvestmentInTheCapitalOrAssetsOfSocialEconomyEntities', 'B2', 'core', 'Financial investment in the capital or assets of social economy entities referred to in the Council Recommendation of 29 September 2023 (excluding donations and contributions)', 'number', NULL),
('GreenhouseGasEmissionReductionTargetBaseYear', 'B3', 'core', 'Year (date)', 'enum', NULL),
('GreenhouseGasEmissionReductionTargetYear', 'B3', 'core', 'Year (date)', 'enum', NULL),
('GrossLocationBasedScope2GreenhouseGasEmissions', 'B3', 'core', 'Gross Scope 2 location-based GHG Emissions', 'number', NULL),
('GrossMarketBasedScope2GreenhouseGasEmissions', 'B3', 'core', 'Gross scope 2 market-based GHG Emissions May (optional)', 'number', NULL),
('GrossScope1GreenhouseGasEmissions', 'B3', 'core', 'Gross Scope 1 GHG Emissions', 'number', NULL),
('LinkToPreviousReportContainingDisclosuresThatRemainUnchanged', 'B1', 'core', 'Link to previous report containing disclosures that remain unchanged', 'string', NULL),
('ListOfDisclosuresForWhichNoChangesAreReportedComparedToThePreviousPeriodReporting', 'B1', 'core', 'List of disclosures for which no changes are reported compared to the previous period reporting', 'enum', NULL),
('ListOfOmittedDisclosuresDeemedToBeClassifiedOrSensitiveInformation', 'B1', 'core', 'List of omitted disclosures deemed to be classified or sensitive information', 'enum', NULL),
('NaceSectorClassificationCodes', 'B1', 'core', 'NACE sector classification code(s)', 'enum', NULL),
('NameOfMaterialUsed', 'B7', 'core', 'Name of the key material', 'string', NULL),
('NameOfTheSubsidiary', 'B1', 'core', 'Name', 'string', NULL),
('NumberOfEmployees', 'B1', 'core', 'Number of employees', 'number', NULL),
('NumberOfEmployeesForCountryOfEmploymentContract', 'B8', 'core', 'Number of employees', 'number', NULL),
('NumberOfFatalitiesAsAResultOfWorkRelatedInjuriesAndWorkRelatedIllHealth', 'B9', 'core', 'Number of fatalities as a result of work-related injuries and work-related ill health', 'number', NULL),
('NumberOfFemaleEmployees', 'B8', 'core', 'Female', 'number', NULL),
('NumberOfMaleEmployees', 'B8', 'core', 'Male', 'number', NULL),
('NumberOfNonReportedGenderEmployees', 'B8', 'core', 'Not reported', 'number', NULL),
('NumberOfOtherGenderEmployees', 'B8', 'core', 'Other', 'number', NULL),
('NumberOfPermanentContractEmployees', 'B8', 'core', 'Permanent contract', 'number', NULL),
('NumberOfRecordableWorkRelatedAccidentsInTheReportingPeriod', 'B9', 'core', 'Number of recordable work-related accidents in the reporting period', 'number', NULL),
('OtherUndertakingsLegalForm', 'B1', 'core', 'Other undertaking''s legal form specification', 'string', NULL),
('PostalCodeOfSite', 'B1', 'core', 'Postal code', 'string', NULL),
('PotentialAdverseEffectsOfClimateRisksThatMayAffectItsFinancialPerformanceOrBusinessOperationsInTheShortMediumOrLongTermIndicatingWhetherItAssessesTheRisksToBeHighMediumOrLow', 'C4', 'comprehensive', 'Potential adverse effects of climate risks that may affect its financial performance or business operations in the short- medium- or long-term indicating whether it assesses the risks to be high medium or low May (optional)', 'string', NULL),
('PracticePolicyAndOrFutureInitiativeIsPubliclyAvailable', 'B2', 'core', 'Undertaking has a practice policy and or future initiative that is publicly available', 'string', NULL),
('PubliclyAvailableDisclosure', 'B4', 'core', 'Is this disclosure already publicly available?', 'string', NULL),
('RegisteredAddressOfTheSubsidiary', 'B1', 'core', 'Registered Address', 'string', NULL),
('ReportContainsDisclosuresFromThePreviousReportingPeriodThatRemainUnchanged', 'B1', 'core', 'This report contains disclosures from the previous reporting period that remain unchanged', 'string', NULL),
('RevenueDerivedFromCoal', 'C8', 'comprehensive', 'Revenue derived from coal', 'string', NULL),
('RevenueDerivedFromControversialWeaponsAntiPersonnelMinesClusterMunitionsChemicalWeaponsAndBiologicalWeapons', 'C8', 'comprehensive', 'Revenue derived from controversial weapons (anti-personnel mines cluster munitions chemical weapons and biological weapons)', 'string', NULL),
('RevenueDerivedFromCultivationAndProductionOfTobacco', 'C8', 'comprehensive', 'Revenue derived from cultivation and production of tobacco', 'string', NULL),
('RevenueDerivedFromGas', 'C8', 'comprehensive', 'Revenue derived from gas', 'string', NULL),
('RevenueDerivedFromChemicalProduction', 'C8', 'comprehensive', 'Revenue derived from chemicals production', 'string', NULL),
('RevenueDerivedFromOil', 'C8', 'comprehensive', 'Revenue derived from oil', 'string', NULL),
('SiteLocatedInABiodiversitySensitiveArea', 'B5', 'core', 'Site located in a biodiversity sensitive area', 'string', NULL),
('SiteLocatedNearABiodiversitySensitiveArea', 'B5', 'core', 'Site located near a biodiversity sensitive area', 'string', NULL),
('SpecificationOfAnyConfirmedIncidentInvolvingWorkersInTheValueChainAffectedCommunitiesConsumersAndEndUsers', 'C7', 'comprehensive', 'Specification of any confirmed incident involving workers in the value chain affected communities consumers and end-users', 'string', NULL),
('SpecificationOfOtherHumanRightsRelatedToTheConfirmedIncident', 'C7', 'comprehensive', 'Specify other human rights related to the confirmed incidents', 'string', NULL),
('SpecificationOfOtherTypesOfContentCoveredByTheCodeOfConductOrHumanRightsPolicy', 'C6', 'comprehensive', 'Specify other types of content covered by the code of conduct or human rights policy', 'string', NULL),
('SustainabilityIssueAddressedByPracticePolicyAndOrFutureInitiative', 'B2', 'core', 'Climate change', 'string', NULL),
('template_currency', 'B1', 'core', 'Currency of the monetary values in the report', 'enum', NULL),
('template_reporting_entity_identifier', 'B1', 'core', 'Identifier of the reporting entity (select and specify on the right)', 'string', NULL),
('template_reporting_entity_identifier_scheme', 'B1', 'core', 'Identifier of the reporting entity (select and specify on the right)', 'enum', NULL),
('template_reporting_entity_name', 'B1', 'core', 'Name of the reporting entity', 'string', NULL),
('TimeHorizonsOfAnyClimateRelatedHazardsAndTransitionEventsIdentified', 'C4', 'comprehensive', 'Time horizons of any climate-related hazards and transition events identified', 'string', NULL),
('TotalAmountOfFinesForTheViolationOfAnticorruptionAndAntibriberyLaws', 'B11', 'core', 'Total amount of fines for the violation of anti-corruption and anti-bribery laws amount in', 'number', NULL),
('TotalAmountOfWaterWithdrawnFromAllSites', 'B6', 'core', 'Total amount of water withdrawn from all sites (cubic meters m)', 'number', NULL),
('TotalEnergyConsumption', 'B3', 'core', 'Total Energy Consumption', 'number', NULL),
('TotalNatureOrientedAreaOffSite', 'B5', 'core', 'Total nature-oriented area off-site', 'number', NULL),
('TotalNatureOrientedAreaOnSite', 'B5', 'core', 'Total nature-oriented area on-site', 'number', NULL),
('TotalNumberOfConvictionsForTheViolationOfAntiCorruptionAndAntiBriberyLaws', 'B11', 'core', 'Total number of convictions  for the violation of anti-corruption and anti-bribery laws', 'number', NULL),
('TotalNumberOfSelfEmployedWorkersWithoutPersonnelThatAreWorkingExclusivelyForTheUndertaking', 'C5', 'comprehensive', 'Total self-employed workers without personnel that are working exclusively for the undertaking', 'number', NULL),
('TotalNumberOfTemporaryWorkersProvidedByUndertakingsPrimarilyEngagedInEmploymentActivities', 'C5', 'comprehensive', 'Total temporary workers provided by undertakings primarily engaged in employment activities', 'number', NULL),
('TotalSealedArea', 'B5', 'core', 'Total sealed area', 'number', NULL),
('TotalUseOfLand', 'B5', 'core', 'Total use of land', 'number', NULL),
('Turnover', 'B1', 'core', 'Turnover in', 'number', NULL),
('TypeOfContentCoveredByTheCodeOfConductOrHumanRightsPolicyForItsOwnWorkforce', 'C6', 'comprehensive', 'child labour', 'string', NULL),
('TypeOfHumanRightRelatedToTheConfirmedIncident', 'C7', 'comprehensive', 'child labour', 'string', NULL),
('TypeOfNumberOfEmployees', 'B1', 'core', 'Employee counting methodology (Headcount or Full-time equivalent)', 'enum', NULL),
('UndertakingAppliesCircularEconomyPrinciples', 'B7', 'core', 'Undertaking applies circular economy principles', 'enum', NULL),
('UndertakingHasACodeOfConductOrHumanRightsPolicyForItsOwnWorkforce', 'C6', 'comprehensive', 'Does the undertaking have a code of conduct or human rights policy for its own workforce?', 'enum', NULL),
('UndertakingHasAComplaintHandlingMechanismForItsOwnWorkforce', 'C6', 'comprehensive', 'Does the undertaking have a complaint-handling mechanism for its own workforce?', 'enum', NULL),
('UndertakingHasConfirmedHumanRightsIncidentsInItsOwnWorkforce', 'C7', 'comprehensive', 'Does the undertaking have confirmed incidents in its own workforce?', 'enum', NULL),
('UndertakingHasSetATargetWhichIsRelatedToAPolicy', 'B2', 'core', 'Undertaking has set a target which is related to a policy', 'string', NULL),
('UndertakingIsAwareOfAnyConfirmedIncidentsInvolvingWorkersInTheValueChainAffectedCommunitiesConsumersAndEndUsers', 'C7', 'comprehensive', 'Is the undertaking aware of any confirmed incidents involving workers in the value chain affected communities consumers and end-users?', 'enum', NULL),
('UndertakingsLegalForm', 'B1', 'core', 'Undertakings legal form', 'string', NULL),
('URLOrLinkToThePubliclyAvailableDisclosure', 'B4', 'core', 'Please provide the relevant URL link or hyperlink of where this information is reported', 'string', NULL),
('VolumeOfMaterialUsed', 'B7', 'core', 'Mass / Volume', 'number', NULL),
('WasteDirectedToDisposalMass', 'B7', 'core', 'Waste directed to disposal', 'number', NULL),
('WasteDirectedToDisposalVolume', 'B7', 'core', 'Waste directed to disposal', 'number', NULL),
('WasteDivertedToRecycleOrReuseMass', 'B7', 'core', 'Waste diverted to recycle or reuse', 'number', NULL),
('WasteDivertedToRecycleOrReuseVolume', 'B7', 'core', 'Waste diverted to recycle or reuse', 'number', NULL),
('WaterDischargeFromUndertakingProductionProcesses', 'B6', 'core', 'Water discharge from undertaking production processes (m)', 'number', NULL),
('WeightOfMaterialUsed', 'B7', 'core', 'Mass / Volume', 'number', NULL);